# Generated by:
#  genmakefile -t xc8 -m gmake -s mingw -I. -Ilib -Isrc src/glcdtest.c lib/delay.c lib/random.c lib/spi.c lib/st7735r.c lib/delay.h lib/random.h lib/spi.h lib/st7735r.h lib/const.h lib/device.h lib/typedef.h src/config-18f25k50.h src/config-bits.h -DPIC18F25K50=1 -D__18f25k50=1 -D_XTAL_FREQ=48000000 -DXTAL_USED=NO_XTAL -DUART_BAUD=38400 -DSPI_USE_HW=1 -D__DEBUG=1 -D_DEBUG=1 --create-bins --no-create-libs --debug --chip=18f25k50 -d build/wine-obj/18f25k50-debug -o glcdtest-18f25k50-xc8-debug.mk
DEFS = -DPIC18F25K50=1 -D__18f25k50=1 -D_XTAL_FREQ=16000000 -DXTAL_USED=NO_XTAL -DUART_BAUD=38400 -DSPI_USE_HW=1 -D__DEBUG=1 -D_DEBUG=1 -D__XC=1 -DNO_PLL
CC = xc8
LINK = mplink
LIB = mplib
TARGET = pic18
CHIP = 18f25k50
CPPFLAGS = -DPIC18=1 -D__$(CHIP)=1 -D__18f25k50=1 -I. -Ilib -Isrc
CFLAGS = --mode=pro --float=24 --double=32 --opt=default,+asm,+asmfile,-speed,-space,+debug -g --debugger=pickit3 -q --asmlist --chip=$(CHIP)
LDFLAGS = --output=-elf,+mcof --summary=default --runtime=default,+clear,+init,-keep,-no_startup,-osccal,-resetbits,+download,+clib --stack=compiled
COMMON_FLAGS = 
BUILDDIR = build/wine-obj/18f25k50-debug/

VPATH = .

.PHONY: all
all: build/wine-obj/18f25k50-debug \
  build/wine-obj/18f25k50-debug/glcdtest.cof


: $(BUILDDIR)%.p1: %.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c $< -o$@

$(BUILDDIR)st7735r.p1: \
  lib/st7735r.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c $< -o$@

$(BUILDDIR)spi.p1: \
  lib/spi.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c $< -o$@

$(BUILDDIR)random.p1: \
  lib/random.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c $< -o$@

$(BUILDDIR)delay.p1: \
  lib/delay.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c $< -o$@

$(BUILDDIR)glcdtest.p1: \
  src/glcdtest.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) --pass1 -c $< -o$@

$(BUILDDIR)glcdtest.cof: \
  build/wine-obj/18f25k50-debug/glcdtest.p1 \
  build/wine-obj/18f25k50-debug/delay.p1 \
  build/wine-obj/18f25k50-debug/random.p1 \
  build/wine-obj/18f25k50-debug/spi.p1 \
  build/wine-obj/18f25k50-debug/st7735r.p1
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(LDFLAGS) $(EXTRA_LDFLAGS) -o$@ $^ $(LIBS) $(EXTRA_LIBS) $(STDC_LIBS)

build/wine-obj/18f25k50-debug:
	IF NOT EXIST build MKDIR build
	IF NOT EXIST build\wine-obj MKDIR build\wine-obj
	IF NOT EXIST build\wine-obj\18f25k50-debug MKDIR build\wine-obj\18f25k50-debug

clean:
	DEL /F build\wine-obj\18f25k50-debug\*.p1
	DEL /F build\wine-obj\18f25k50-debug\*.cof

