# Generated by:
#  /usr/local/bin/genmakefile -m make -t gputils insider_v1_628.asm --create-objs --create-bins -o Makefile
CC = gpasm
LINK = gplink
LIB = gplib
MACH = pic14
CHIP = 16f876a
CFLAGS = -p$(CHIP)
CPPFLAGS = -D__$(CHIP)=1 -DGPUTILS=1 -D__16f876a=1
DEFS = -DNDEBUG=1

all: build/gputils-16f876a/Release /home/roman/Projects/pictest
build/gputils-16f876a/Release:
	mkdir -p build/gputils-16f876a/Release

/home/roman/Projects/pictest:
	mkdir -p /home/roman/Projects/pictest

