#include "config-bits.h"
#include "pictest.h"

#include "../lib/const.h"
#include "../lib/device.h"
#include "../lib/interrupt.h"
#include "../lib/softpwm.h"
#include "../lib/timer.h"
#include "bresenham.h"

#ifdef USE_USB
// Included up here, not down by the rest of the USE_USB section below --
// INTERRUPT_FN() (right below) already calls usb_tasks() and references
// USB_INTERRUPT_ENABLE/FLAG, both declared in these headers. The literal
// EP0_*/CDC_*_BUFFER_BASE_ADDR overrides usb.h/usb_cdc.h's #ifndef guards
// pick up are passed as -D flags from build/vars.mk (USE_USB block), not
// included here, since usb.c/usb_cdc_acm.c need them too and don't include
// any rgbtest-specific header.
#include "usb.h"
#include "usb_cdc.h"
#endif

// SOFTPWM_RANGE (lib/softpwm.h) is the actual duty-cycle ceiling the ISR
// compares against -- softpwm_set() values above it just stay full-on,
// so every color value here is expressed directly in 0..SOFTPWM_RANGE.
//
// Default softpwm pin assignment (lib/softpwm.h: PORTC, pins 0-2) puts
// R/G/B on RC0/RC1/RC2 -- picstick_25k50 JP1-14/13/12 (DIP 11/12/13, see
// picstick.md SS1) -- all confirmed free/plain GPIO, clear of the
// on-board User LED (RA4/JP1-6), the reset chain (JP2-1/10), the
// ICSP-shared PORTB pins (JP2-2/3/13/14) and the optional-crystal pins
// (RA6/RA7). Wire each of R/G/B through its own current-limiting
// resistor (a common LED needs ~150-330R at 5V depending on color/LED;
// size it per the LED's actual datasheet) to the RGB LED's cathode(s)
// for a common-anode LED, or invert every softpwm_set() value below
// (SOFTPWM_RANGE - x) for a common-cathode one.

#if defined(__SDCC__) && defined(PIC16)
__code unsigned int __at(_CONFIG) __config_word = CONFIG_WORD;
#endif

volatile uint32_t msecs;
BRESENHAM_DECL(bres);

// Heartbeat PWM for the picstick's onboard User LED (RA4/JP1-6, D2 via
// R4 -- see picstick.md SS3) -- a plain free-running 8-bit soft-PWM
// counter driven straight off every Timer0 overflow, independent of
// lib/softpwm.h (which only owns PORTC/RC0-2 for the RGB LED). At
// Timer0's raw overflow rate this wraps well above the flicker-fusion
// threshold even though it shares the tick with the 1ms msecs count.
volatile uint8_t heartbeat_duty;
static uint8_t heartbeat_pwm_counter;

INTERRUPT_FN() {
  if(TIMER0_INTERRUPT_FLAG) {
    BRESENHAM_INC8(bres);

    if(BRESENHAM_COND(bres, OSC_4 / 1000)) {
      BRESENHAM_SUB(bres, OSC_4 / 1000);
      msecs++;
    }

    OUTA4 = (heartbeat_pwm_counter++ < heartbeat_duty) ? 1 : 0;

    TIMER0_INTERRUPT_CLEAR();
  }

  SOFTPWM_ISR();

#ifdef USE_USB
  // Matches CDC_Serial_Example.X/main.c: the stack's own state machine
  // runs from the interrupt, not polled from the main loop.
  if(USB_INTERRUPT_ENABLE && USB_INTERRUPT_FLAG) {
    usb_tasks();
  }
#endif
}

// Rainbow table generated by tools/make-hue-table.c's hsv2rgb_rainbow(),
// which uses non-uniform hue-segment widths (narrower in the red/green
// straddle around orange->yellow) specifically so yellow stays visibly
// distinct while fading through the rainbow -- plain-uniform HSV->RGB
// left yellow essentially invisible on a ping-pong-ball-diffused LED.
// This is the exact algorithm/tuning from src/blinktest.c's embedded
// rainbow8[] (steps=128, sat=255, intensity=255, gamma=1.0), regenerated
// at `range=SOFTPWM_RANGE` (100) instead of blinktest.c's raw 0-255,
// since lib/softpwm.h's real duty-cycle domain is 0..100, not 0..255 --
// reproduce with:
//   tools/make-hue-table 128 false 255 255 100 2 1.0
#define RAINBOW_STEPS 128
#define RAINBOW_MASK ((RAINBOW_STEPS) - 1)

static const uint8_t rainbow8[RAINBOW_STEPS][3] = {
    {100, 0, 0},   {100, 4, 0},  {100, 8, 0},  {100, 13, 0}, {100, 17, 0}, {100, 21, 0}, {100, 25, 0}, {100, 29, 0},
    {100, 33, 0},  {100, 38, 0}, {100, 42, 0}, {100, 46, 0}, {100, 50, 0}, {100, 54, 0}, {100, 58, 0}, {100, 63, 0},
    {100, 67, 0},  {100, 69, 0}, {100, 71, 0}, {100, 73, 0}, {100, 75, 0}, {100, 77, 0}, {100, 79, 0}, {100, 81, 0},
    {100, 83, 0},  {100, 85, 0}, {100, 88, 0}, {100, 90, 0}, {100, 92, 0}, {100, 94, 0}, {100, 96, 0}, {100, 98, 0},
    {100, 100, 0}, {94, 100, 0}, {88, 100, 0}, {81, 100, 0}, {75, 100, 0}, {69, 100, 0}, {63, 100, 0}, {56, 100, 0},
    {50, 100, 0},  {44, 100, 0}, {38, 100, 0}, {31, 100, 0}, {25, 100, 0}, {19, 100, 0}, {13, 100, 0}, {6, 100, 0},
    {0, 100, 0},   {0, 98, 2},   {0, 96, 4},   {0, 94, 6},   {0, 92, 8},   {0, 90, 10},  {0, 88, 13},  {0, 85, 15},
    {0, 83, 17},   {0, 81, 19},  {0, 79, 21},  {0, 77, 23},  {0, 75, 25},  {0, 73, 27},  {0, 71, 29},  {0, 69, 31},
    {0, 67, 33},   {0, 63, 38},  {0, 58, 42},  {0, 54, 46},  {0, 50, 50},  {0, 46, 54},  {0, 42, 58},  {0, 38, 63},
    {0, 33, 67},   {0, 29, 71},  {0, 25, 75},  {0, 21, 79},  {0, 17, 83},  {0, 13, 88},  {0, 8, 92},   {0, 4, 96},
    {0, 0, 100},   {2, 0, 98},   {4, 0, 96},   {6, 0, 94},   {8, 0, 92},   {10, 0, 90},  {13, 0, 88},  {15, 0, 85},
    {17, 0, 83},   {19, 0, 81},  {21, 0, 79},  {23, 0, 77},  {25, 0, 75},  {27, 0, 73},  {29, 0, 71},  {31, 0, 69},
    {33, 0, 67},   {35, 0, 65},  {38, 0, 63},  {40, 0, 60},  {42, 0, 58},  {44, 0, 56},  {46, 0, 54},  {48, 0, 52},
    {50, 0, 50},   {52, 0, 48},  {54, 0, 46},  {56, 0, 44},  {58, 0, 42},  {60, 0, 40},  {63, 0, 38},  {65, 0, 35},
    {67, 0, 33},   {69, 0, 31},  {71, 0, 29},  {73, 0, 27},  {75, 0, 25},  {77, 0, 23},  {79, 0, 21},  {81, 0, 19},
    {83, 0, 17},   {85, 0, 15},  {88, 0, 13},  {90, 0, 10},  {92, 0, 8},   {94, 0, 6},   {96, 0, 4},   {98, 0, 2},
};

// 250ms/step (~32s per full 128-step rainbow cycle) is blinktest.c's own
// tuned rate, not a placeholder -- kept as-is rather than re-timed.
#define CYCLE_MSECS_PER_STEP 250

// Heartbeat: swell up over most of the period, then cut sharply to off
// for the remainder -- not a symmetric fade in both directions. Period
// 700ms is ~1.43Hz, inside the requested 1-2Hz range.
#define HEARTBEAT_PERIOD_MS 700
#define HEARTBEAT_RISE_MS 550

static void
heartbeat_tasks(void) {
  uint16_t phase = (uint16_t)(msecs % HEARTBEAT_PERIOD_MS);

  if(phase < HEARTBEAT_RISE_MS) {
    // Quadratic ease-in so the rise itself feels like a swell rather
    // than a linear ramp.
    uint16_t t = (uint16_t)((uint32_t)phase * 255 / HEARTBEAT_RISE_MS);

    heartbeat_duty = (uint8_t)((uint32_t)t * t / 255);
  } else {
    heartbeat_duty = 0; // abrupt stop
  }
}

#ifdef USE_USB
// ---------------------------------------------------------------------
// USB CDC command interface (optional) -- see rgbtest.md for the
// integration method/rationale. Kept as its own section so the base
// lamp builds and runs identically with USE_USB left undefined.
// ---------------------------------------------------------------------
static uint8_t usb_line[32];
static uint8_t usb_line_len;

// lamp state the CDC command handler and the main loop share
static volatile uint8_t usb_override_active;
static volatile uint8_t usb_override_rgb[3];

static void
usb_cmd_handle(uint8_t* line, uint8_t len) {
  // "C r g b\r\n" (each 0..SOFTPWM_RANGE) -- freeze the lamp to one color
  // "R\r\n"       -- resume the rainbow cycle
  if(len >= 1 && (line[0] == 'R' || line[0] == 'r')) {
    usb_override_active = 0;
  } else if(len >= 1 && (line[0] == 'C' || line[0] == 'c')) {
    uint8_t vals[3] = {0, 0, 0};
    uint8_t vi = 0, i = 1;

    while(i < len && vi < 3) {
      while(i < len && line[i] == ' ') i++;

      uint16_t n = 0;
      while(i < len && line[i] >= '0' && line[i] <= '9') {
        n = n * 10 + (line[i] - '0');
        i++;
      }

      vals[vi++] = (uint8_t)(n > SOFTPWM_RANGE ? SOFTPWM_RANGE : n);
    }

    usb_override_rgb[0] = vals[0];
    usb_override_rgb[1] = vals[1];
    usb_override_rgb[2] = vals[2];
    usb_override_active = 1;
  }
}

// cdc_data_out()/cdc_data_in() are called from cdc_tasks(), which itself
// runs from the USB ISR (see the USB_INTERRUPT_ENABLE/FLAG check in
// INTERRUPT_FN() above) -- so, matching CDC_Serial_Example.X/main.c's own
// cdc_data_out()/serial_echo() split, these just set a flag and leave the
// actual g_cdc_dat_ep_out copy/re-arm to the main loop.
static volatile uint8_t usb_rx_pending;

void
cdc_data_out(void) {
  usb_rx_pending = 1;
}

void
cdc_data_in(void) {}

void
cdc_notification(void) {}

void
cdc_set_control_line_state(void) {}

void
cdc_set_line_coding(void) {}

static void
usb_rx_tasks(void) {
  if(!usb_rx_pending)
    return;

  usb_rx_pending = 0;

  for(uint8_t i = 0; i < g_cdc_num_data_out; i++) {
    uint8_t ch = g_cdc_dat_ep_out[i];

    if(ch == '\r' || ch == '\n') {
      if(usb_line_len) {
        usb_cmd_handle(usb_line, usb_line_len);
        usb_line_len = 0;
      }
    } else if(usb_line_len < sizeof(usb_line)) {
      usb_line[usb_line_len++] = ch;
    }
  }

  cdc_arm_data_ep_out();
}
#endif

int
main(void) {
  uint32_t next_step = 0;
  uint16_t index = 0;

  timer0_init(PRESCALE_1_1 | TIMER0_FLAGS_8BIT);
  TIMER0_INTERRUPT_CLEAR();
  TMR0IE = 1;

  TRISA4 = 0;

  softpwm_init();

#ifdef USE_USB
  usb_init();
#endif

  PEIE = 1;
  INTERRUPT_ENABLE();

  for(;;) {
    heartbeat_tasks();

#ifdef USE_USB
    usb_rx_tasks();

    if(usb_override_active) {
      softpwm_set(0, usb_override_rgb[0]);
      softpwm_set(1, usb_override_rgb[1]);
      softpwm_set(2, usb_override_rgb[2]);
    } else
#endif
        if(msecs >= next_step) {
      const uint8_t* rgb = rainbow8[index++ & RAINBOW_MASK];

      next_step = msecs + CYCLE_MSECS_PER_STEP;

      softpwm_set(0, rgb[0]);
      softpwm_set(1, rgb[1]);
      softpwm_set(2, rgb[2]);
    }
  }
}
